REC/REC/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from django.contrib.auth import views
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('realEstate.urls')),
    path('account/', include('account.urls')),
    url(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    url(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
]

# Image file

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

REC/realEstate/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'realEstate'
urlpatterns = [

    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('customer/create/', views.customer_new, name='customer_new'),
    path('property_list', views.property_list, name='property_list'),
    path('property/<int:pk>/edit/', views.property_edit, name='property_edit'),
    path('property/<int:pk>/delete/', views.property_delete, name='property_delete'),
    path('property/create', views.property_new, name='property_new'),

    path('admin_home', views.admin_home, name='admin_home'),
    path('property_summary_pdf', views.property_summary_pdf, name='property_summary_pdf'),
]

REC/realEstate/models.py
from django.db import models
from django.utils import timezone

purpose = (
    ('For Sale', 'For Sale'),
    ('For Lease', 'For Lease')
)

type = (
    ('Condo', 'Condo'),
    ('House', 'House'),
    ('Apartment', 'Apartment')
)


# Customer Model
class Customer(models.Model):
    cust_id = models.IntegerField()
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    email = models.EmailField(max_length=200, default='Null')
    phone = models.CharField(max_length=50)
    maxPrice = models.IntegerField()
    minPrice = models.IntegerField()
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.fname)


# Properties Model
class Property (models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='customers')
    prop_number = models.CharField(max_length=50)
    type = models.CharField(max_length=20, choices=type, default='Condo', blank=False)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    dimension = models.CharField(max_length=50)
    price = models.IntegerField()
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    bed = models.CharField(max_length=50)
    bath = models.CharField(max_length=50)
    build = models.CharField(max_length=50)
    purpose = models.CharField(max_length=10, choices=purpose, default='For Sale', blank=False)
    status = models.BooleanField(default='True')

    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

REC/realEstate/forms.py
from django import forms
from .models import Customer
from .models import Property


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_id', 'fname', 'lname', 'address', 'city', 'state', 'zipcode','email', 'phone','maxPrice','minPrice',)


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ('customer', 'prop_number', 'type', 'address', 'city', 'state', 'zipcode', 'dimension', 'price','image','bed','bath', 'build', 'purpose', 'status',)

REC/realEstate/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from .models import *
from .forms import *
from django.utils import timezone
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.auth.decorators import permission_required
from .utils import render_to_pdf
from django.template.loader import get_template
now = timezone.now()


def getActiveEvent():
    activeEvent = Property.objects.filter(event_end_date__isnull=True)
    return activeEvent


# Creating our view, it is a class based view
class GeneratePdf(View):
    def get(self, request, *args, **kwargs):
        # getting the template
        pdf = render_to_pdf('pdf.html')

        # rendering the template
        return HttpResponse(pdf, content_type='application/pdf')


def home(request):
    return render(request, 'realEstate/home.html', {'realEstate': home})


# Customer_List
@login_required
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'realEstate/customer_list.html', {'customers': customer})


@login_required
def customer_edit(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == "POST":
        # update
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.updated_date = timezone.now()
            customer.save()
            customer = Customer.objects.filter(created_date__lte=timezone.now())
            return render(request, 'realEstate/customer_list.html', {'customers': customer})

    else:
        # edit
        form = CustomerForm(instance=customer)
    return render(request, 'realEstate/customer_edit.html', {'form': form})


# customer_delete
@login_required
def customer_delete(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customer.delete()
    return redirect('realEstate:customer_list')


# customer_Add
@login_required
def customer_new(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.created_date = timezone.now()
            customer.save()
            customer = Customer.objects.filter(created_date__lte=timezone.now())
            return render(request, 'realEstate/customer_list.html',
                          {'customers': customer})
    else:
        form = CustomerForm()
        # print("Else")
    return render(request, 'realEstate/customer_new.html', {'form': form})


# property_list
@login_required
def property_list(request):
    propertys = Property.objects.filter(created_date__lte=timezone.now())
    return render(request, 'realEstate/property_list.html',
                  {'propertys': propertys})


# property_edit
@login_required
def property_edit(request, pk):
    property = get_object_or_404(Property, pk=pk)
    if request.method == "POST":
        # update
        form = PropertyForm(request.POST, instance=property)
        if form.is_valid():
            property = form.save(commit=False)
            property.updated_date = timezone.now()
            property.save()
            propertys = Property.objects.filter(created_date__lte=timezone.now())
            return render(request, 'realEstate/property_list.html',
                          {'propertys': propertys})
    else:
        # edit
        form = PropertyForm(instance=property)
    return render(request, 'realEstate/property_edit.html', {'form': form})


# property_delete
@login_required
def property_delete(request, pk):
    property = get_object_or_404(Property, pk=pk)
    property.delete()
    return redirect('realEstate:property_list')


# Property_Add
@login_required
def property_new(request):
    if request.method == "POST":
        form = PropertyForm(request.POST)
        if form.is_valid():
            property = form.save(commit=False)
            property.created_date = timezone.now()
            property.save()
            propertys = Property.objects.filter(created_date__lte=timezone.now())
            return render(request, 'realEstate/property_list.html',
                          {'propertys': propertys})
    else:
        form = PropertyForm()
        # print("Else")
    return render(request, 'realEstate/property_new.html', {'form': form})


@login_required
def property_summary_pdf(request):
    global propertys
    propertys = Property.objects.filter(created_date__lte=timezone.now())
    context = {'property': propertys,}
    template = get_template('realEstate/property_summary_pdf.html')
    html = template.render(context)
    pdf = render_to_pdf('realEstate/property_summary_pdf.html', context)
    return pdf


@permission_required('is_superuser')
def admin_home(request):

        return render(request, 'realEstate/admin_home.html',
                      {'admin': admin_home})

REC/realEstate/templates/realEstate/admin_base.html
{% load static %}

<html lang="en">
<head>

    <title>Real Estate Sales Companion</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }
        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }
        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }
        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }
            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout" class="body" background="{% static 'images/background.jpg' %}" style="height: 100%;
  background-repeat: no-repeat;background-size: cover;">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <img src="{% static 'images/property1.jpg' %}" width="100" height="70" alt="logo"/>

            <a class="navbar-brand" href="{% url 'realEstate:home' %}" style="float: right">Real Estate Sales Companion</a>

        </div>
        <div class="collapse navbar-collapse" id="myNavbar" style="float: right;">
            <ul class="nav navbar-nav">

                {% if user.is_authenticated %}

                    <li><a href="{% url 'realEstate:admin_home' %}">Admin</a></li>
                {% endif %}


            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                           More options <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>

                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

<div class="content container">
    <div class="row">
        <div class="col-md-10">
            {% block content %}
            {% endblock %}
            </div>
        </div>


</div>
</body>
</html>

REC/realEstate/templates/realEstate/admin_home.html
{% extends 'realEstate/admin_base.html' %}
{% load static %}
{% block content %}

    {% if user.is_authenticated %}
        <div class="page-container">
            <h2 class="top-menu">Welcome {{ user.username }},</h2>
            <p>Please choose from below options.</p>
        </div>
    {% endif %}

    <div class="content container">
        <div class="row" style="width:100%">
            <div class="col-md-12" style="width: 100%">
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="col-md-3">
                        <div class="thumbnail">
                            <a href="{% url 'realEstate:property_summary_pdf' %}" class="row">
                                <span class="btn btn-primary">Property Report</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

REC/realEstate/templates/realEstate/base.html
{% load static %}

<html lang="en">
<head>
    <title>Real Estate Sales Companion</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                Real Estate Sales Companion
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'realEstate:home' %}">Home</a></li>
                <li><a href="{% url 'realEstate:customer_list' %}">Customers</a></li>
                <li><a href="{% url 'realEstate:property_list' %}">Properties</a></li>
                {% if user.is_authenticated %}
                        {% if user.is_superuser%}
                            <li><a href="{% url 'realEstate:admin_home' %}">Admin</a></li>
                        {% endif %}
                {% endif %}

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/customer.jpg" %}" alt="customer"/>
                                <div class="caption">
                                    <h2>Customer</h2>
                                    <p>We see our success in our customers success, it gives us an immense pleasure when
                                        our
                                        advises
                                        turn out to be fruitful. </p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href="{% url 'realEstate:customer_list' %}"
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/property1.jpg" %}" alt="property"/>
                                <div class="caption">
                                    <h2>Properties</h2>
                                    <p>Property details are provided here!</p>
                                    <p><a class="btn btn-default" href="{% url 'realEstate:property_list' %}"
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</body>
</html>

REC/realEstate/templates/realEstate/customer_delete.html
{% block body_block %}
    <h1>Delete {{ customer.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'realEstate:home' pk=customer.cust_number %} ">Cancel</a>
    </form>
{% endblock %}

REC/realEstate/templates/realEstate/customer_edit.html
{% extends 'realEstate/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Customer</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

REC/realEstate/templates/realEstate/customer_list.html
{% extends 'realEstate/base.html' %}
{% block content %}
    {% load static %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Real Estate Companion</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Real Estate Sales Companion, Real Estate Agents Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Customer Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Cust_id</th>
                <th>Fname</th>
                <th>Lname</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zipcode</th>
                <th>Phone</th>
                <th>Maximum Price</th>
                <th>Minimum Price</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.cust_id }}</td>
                    <td>{{ customer.fname }}</td>
                    <td>{{ customer.lname }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.phone }}</td>
                    <td>{{ customer.maxPrice }}</td>
                    <td>{{ customer.minPrice }}</td>
                    <td><a href="{% url 'realEstate:customer_edit' pk=customer.pk %}" class="btn btn-warning">Edit</a>
                     <td><a href="{% url 'realEstate:customer_delete' pk=customer.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
                 <a href="{% url 'realEstate:customer_new' %}" class="row"><span
                            class="btn btn-primary">Add Customer</span></a>
             </div>

    </div>
    </body>
    </html>
{% endblock %}

REC/realEstate/templates/realEstate/customer_new.html
{% extends 'realEstate/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New Customer</h1>
    <form method="POST" class="customer_form">{% csrf_token %}
          {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

REC/realEstate/templates/realEstate/home.html
{% extends 'realEstate/base.html' %}
{% load static %}
{% block content %}
            {% if user.is_authenticated %}
                <div class="page-container">

                    <h2 class="top-menu">Hello {{ user.username }},</h2>
                    <p>Please choose from below options.</p>

                </div>
            {% endif %}
            <div class="content container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="links">
                            <!-- Example row of columns -->
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="thumbnail">
                                        <img src="{% static "images/customer.jpg" %}" alt="customer"/>
                                        <div class="caption">
                                            <h2>Customer</h2>
                                            <p>We see our success in our customers success!!</p>
                                            <p><a class="btn btn-primary" href="{% url 'realEstate:customer_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="thumbnail">
                                        <img src="{% static "images/property1.jpg" %}" alt="property"/>
                                        <div class="caption">
                                            <h2>Properties</h2>
                                            <p>Property details are provided here!</p>
                                            <p><a class="btn btn-primary" href="{% url 'realEstate:property_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </body>
    </html>
{% endblock %}

REC/realEstate/templates/realEstate/pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django HTMLtoPDF Tutorial</title>
</head>
<body>
    <h1>HTML To PDF</h1>
     <b>I'm building web-based, data-driven apps using Django. <br>
Eventually (or unfortunately), I will need to generate some reports that are printer-friendly. <b>
Logically, PDF is the format for such files... <br>
so how am I going to convert my xHTML and CSS to a nice-looking PDF document?<br>

The Django Book has a whole chapter dedicated to Generating Non-HTML Content.<br>
They seem to to be fond of ReportLab ToolKit.<br>
 The caveat here, though, is that you need to know a bit about the internals of a PDF document.<br>
If you're familiar with this, the ReportLab toolkit seems to be the way to go! It has many features, and it seems to be a powerful PDF-generating tool.
</b>
</body>
</html>

REC/realEstate/templates/realEstate/property_delete.html
{% extends 'realEstate/base.html' %}
{% block body_block %}
    <h1>Delete {{ property.prop_number }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'realEstate:home' pk=property.customer%} ">Cancel</a>
    </form>
{% endblock %}

REC/realEstate/templates/realEstate/property_edit.html
{% extends 'realEstate/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Property</h1>
    <form method="POST" class="property-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

REC/realEstate/templates/realEstate/property_new.html
{% extends 'realEstate/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New Property</h1>
    <form method="POST" class="property_form">{% csrf_token %}
          {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

REC/realEstate/templates/realEstate/property_summary.html
{% extends 'realEstate/base.html' %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome!</div>
                <div class="panel-body">
                    Real Estate Companion For Your Success!
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <h2 style="padding-left: 15Px">Customer Property Summary</h2>

</div>

    <div class="row">
        <h3 style="padding-left: 15Px">Property Informations</h3>
    </div>
    <div class="row">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Property</th>
                <th>Property Type</th>
                <th>Dimension</th>
                <th>Price</th>
                <th>Bed</th>
                <th>Bath</th>
                <th>Status</th>

            </tr>
            </thead>
            <tbody>
            {% for property in propertys %}
                <tr>
                    <td>{{ property.prop_number }}</td>
                     <td>{{ property.type }}</td>
                    <td>{{ property.dimension }}</td>
                     <td>{{ property.price }}</td>
                     <td>{{ property.bed }}</td>
                    <td>{{ property.bath }}</td>
                    <td>{{ property.purpose }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>




{% endblock %}